#! /usr/bin/env perl
#
# Andrew Janke - a.janke@gmail.com
#
# Copyright Andrew Janke, The University of Queensland.
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted,
# provided that the above copyright notice appear in all copies.  The
# author and the University make no representations about the
# suitability of this software for any purpose.  It is provided "as is"
# without express or implied warranty.
#
# USE AT OWN RISK!  THIS MAY MUNGE YOUR MINC FILES HEADER!

use warnings "all";
use File::Basename;

$me = &basename($0);
if($#ARGV != 0){
   die "\n+++WARNING: THIS SCRIPT MAY MUNGE YOUR FILE PERMANENTLY!+++\n\n".
       "Usage: $me <file_to_clean.mnc>\n\n";
   }

(@yukky_vars) = split(' ', `mincinfo -varnames $ARGV[0]`);

foreach $var (grep {/spi/} @yukky_vars){
   foreach (split(' ', `mincinfo -varatts $var $ARGV[0]`)){
      print " | [$ARGV[0]] - removing $var:$_\n";
      system('minc_modify_header', '-delete', "$var:$_", $ARGV[0]) == 0 or die;
      }
   }
